import React from 'react'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderCompanent from "@/src/common/header/HeaderCompanent";
import FooterCompanent from "@/src/common/footer/FooterCompanent";
import { ThemeProvider } from "@/src/utils/ThemeProvider/ThemeProvider"
import { Toaster } from "@/src/ui/sonner"
// import '@/i18n'
// import '../i18n'
// import { useTranslation } from 'react-i18next';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <HeaderCompanent/>
            {children}
            <Toaster/>
          <FooterCompanent/>
        </ThemeProvider>
      </body>
    </html>
  );
}
